validation: sovereign
version: 1
build:
    main: ./cmd/govchaind
    proto:
        path: ""
accounts:
    - name: alice
      coins:
        - 20000token
        - 200000000stake
    - name: bob
      coins:
        - 10000token
        - 100000000stake
faucet:
    name: bob
    coins:
        - 5token
        - 100000stake
client:
    typescript:
        path: ts-client
    openapi:
        path: docs/static/openapi.json
default_denom: stake
validators:
    - name: alice
      bonded: 100000000stake
    - name: validator1
      bonded: 200000000stake
    - name: validator2
      bonded: 100000000stake
